namespace Proyecto_Computer
{
    partial class Clientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Clientes));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btnagregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnbuscar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnmodificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btneliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtnombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txttelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtcorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtdireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.datetimepicker = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnagregar
            // 
            this.btnagregar.AllowAnimations = true;
            this.btnagregar.AllowMouseEffects = true;
            this.btnagregar.AllowToggling = false;
            this.btnagregar.AnimationSpeed = 200;
            this.btnagregar.AutoGenerateColors = false;
            this.btnagregar.AutoRoundBorders = false;
            this.btnagregar.AutoSizeLeftIcon = true;
            this.btnagregar.AutoSizeRightIcon = true;
            this.btnagregar.BackColor = System.Drawing.Color.Transparent;
            this.btnagregar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnagregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnagregar.BackgroundImage")));
            this.btnagregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnagregar.ButtonText = "Agregar";
            this.btnagregar.ButtonTextMarginLeft = 0;
            this.btnagregar.ColorContrastOnClick = 45;
            this.btnagregar.ColorContrastOnHover = 45;
            this.btnagregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnagregar.CustomizableEdges = borderEdges1;
            this.btnagregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnagregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnagregar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnagregar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnagregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnagregar.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnagregar.ForeColor = System.Drawing.Color.Black;
            this.btnagregar.IconLeft = null;
            this.btnagregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnagregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnagregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnagregar.IconMarginLeft = 11;
            this.btnagregar.IconPadding = 10;
            this.btnagregar.IconRight = null;
            this.btnagregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnagregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnagregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnagregar.IconSize = 25;
            this.btnagregar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnagregar.IdleBorderRadius = 0;
            this.btnagregar.IdleBorderThickness = 0;
            this.btnagregar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnagregar.IdleIconLeftImage = null;
            this.btnagregar.IdleIconRightImage = null;
            this.btnagregar.IndicateFocus = false;
            this.btnagregar.Location = new System.Drawing.Point(711, 101);
            this.btnagregar.Name = "btnagregar";
            this.btnagregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnagregar.OnDisabledState.BorderRadius = 1;
            this.btnagregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnagregar.OnDisabledState.BorderThickness = 1;
            this.btnagregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnagregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnagregar.OnDisabledState.IconLeftImage = null;
            this.btnagregar.OnDisabledState.IconRightImage = null;
            this.btnagregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnagregar.onHoverState.BorderRadius = 1;
            this.btnagregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnagregar.onHoverState.BorderThickness = 1;
            this.btnagregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnagregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnagregar.onHoverState.IconLeftImage = null;
            this.btnagregar.onHoverState.IconRightImage = null;
            this.btnagregar.OnIdleState.BorderColor = System.Drawing.Color.Chartreuse;
            this.btnagregar.OnIdleState.BorderRadius = 1;
            this.btnagregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnagregar.OnIdleState.BorderThickness = 1;
            this.btnagregar.OnIdleState.FillColor = System.Drawing.Color.Chartreuse;
            this.btnagregar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnagregar.OnIdleState.IconLeftImage = null;
            this.btnagregar.OnIdleState.IconRightImage = null;
            this.btnagregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnagregar.OnPressedState.BorderRadius = 1;
            this.btnagregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnagregar.OnPressedState.BorderThickness = 1;
            this.btnagregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnagregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnagregar.OnPressedState.IconLeftImage = null;
            this.btnagregar.OnPressedState.IconRightImage = null;
            this.btnagregar.Size = new System.Drawing.Size(128, 44);
            this.btnagregar.TabIndex = 0;
            this.btnagregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnagregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnagregar.TextMarginLeft = 0;
            this.btnagregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnagregar.UseDefaultRadiusAndThickness = true;
            this.btnagregar.Click += new System.EventHandler(this.btnagregar_Click);
            // 
            // btnbuscar
            // 
            this.btnbuscar.AllowAnimations = true;
            this.btnbuscar.AllowMouseEffects = true;
            this.btnbuscar.AllowToggling = false;
            this.btnbuscar.AnimationSpeed = 200;
            this.btnbuscar.AutoGenerateColors = false;
            this.btnbuscar.AutoRoundBorders = false;
            this.btnbuscar.AutoSizeLeftIcon = true;
            this.btnbuscar.AutoSizeRightIcon = true;
            this.btnbuscar.BackColor = System.Drawing.Color.Transparent;
            this.btnbuscar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnbuscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnbuscar.BackgroundImage")));
            this.btnbuscar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbuscar.ButtonText = "Buscar";
            this.btnbuscar.ButtonTextMarginLeft = 0;
            this.btnbuscar.ColorContrastOnClick = 45;
            this.btnbuscar.ColorContrastOnHover = 45;
            this.btnbuscar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnbuscar.CustomizableEdges = borderEdges2;
            this.btnbuscar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnbuscar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnbuscar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnbuscar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnbuscar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnbuscar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnbuscar.ForeColor = System.Drawing.Color.Black;
            this.btnbuscar.IconLeft = null;
            this.btnbuscar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnbuscar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnbuscar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnbuscar.IconMarginLeft = 11;
            this.btnbuscar.IconPadding = 10;
            this.btnbuscar.IconRight = null;
            this.btnbuscar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnbuscar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnbuscar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnbuscar.IconSize = 25;
            this.btnbuscar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnbuscar.IdleBorderRadius = 0;
            this.btnbuscar.IdleBorderThickness = 0;
            this.btnbuscar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnbuscar.IdleIconLeftImage = null;
            this.btnbuscar.IdleIconRightImage = null;
            this.btnbuscar.IndicateFocus = false;
            this.btnbuscar.Location = new System.Drawing.Point(711, 166);
            this.btnbuscar.Name = "btnbuscar";
            this.btnbuscar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnbuscar.OnDisabledState.BorderRadius = 1;
            this.btnbuscar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbuscar.OnDisabledState.BorderThickness = 1;
            this.btnbuscar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnbuscar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnbuscar.OnDisabledState.IconLeftImage = null;
            this.btnbuscar.OnDisabledState.IconRightImage = null;
            this.btnbuscar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnbuscar.onHoverState.BorderRadius = 1;
            this.btnbuscar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbuscar.onHoverState.BorderThickness = 1;
            this.btnbuscar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnbuscar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnbuscar.onHoverState.IconLeftImage = null;
            this.btnbuscar.onHoverState.IconRightImage = null;
            this.btnbuscar.OnIdleState.BorderColor = System.Drawing.Color.DarkViolet;
            this.btnbuscar.OnIdleState.BorderRadius = 1;
            this.btnbuscar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbuscar.OnIdleState.BorderThickness = 1;
            this.btnbuscar.OnIdleState.FillColor = System.Drawing.Color.DarkViolet;
            this.btnbuscar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnbuscar.OnIdleState.IconLeftImage = null;
            this.btnbuscar.OnIdleState.IconRightImage = null;
            this.btnbuscar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnbuscar.OnPressedState.BorderRadius = 1;
            this.btnbuscar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbuscar.OnPressedState.BorderThickness = 1;
            this.btnbuscar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnbuscar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnbuscar.OnPressedState.IconLeftImage = null;
            this.btnbuscar.OnPressedState.IconRightImage = null;
            this.btnbuscar.Size = new System.Drawing.Size(128, 46);
            this.btnbuscar.TabIndex = 1;
            this.btnbuscar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnbuscar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnbuscar.TextMarginLeft = 0;
            this.btnbuscar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnbuscar.UseDefaultRadiusAndThickness = true;
            this.btnbuscar.Click += new System.EventHandler(this.btnbuscar_Click);
            // 
            // btnmodificar
            // 
            this.btnmodificar.AllowAnimations = true;
            this.btnmodificar.AllowMouseEffects = true;
            this.btnmodificar.AllowToggling = false;
            this.btnmodificar.AnimationSpeed = 200;
            this.btnmodificar.AutoGenerateColors = false;
            this.btnmodificar.AutoRoundBorders = false;
            this.btnmodificar.AutoSizeLeftIcon = true;
            this.btnmodificar.AutoSizeRightIcon = true;
            this.btnmodificar.BackColor = System.Drawing.Color.Transparent;
            this.btnmodificar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnmodificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnmodificar.BackgroundImage")));
            this.btnmodificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnmodificar.ButtonText = "Modificar\r\n";
            this.btnmodificar.ButtonTextMarginLeft = 0;
            this.btnmodificar.ColorContrastOnClick = 45;
            this.btnmodificar.ColorContrastOnHover = 45;
            this.btnmodificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnmodificar.CustomizableEdges = borderEdges3;
            this.btnmodificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnmodificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnmodificar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnmodificar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnmodificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnmodificar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnmodificar.ForeColor = System.Drawing.Color.Black;
            this.btnmodificar.IconLeft = null;
            this.btnmodificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnmodificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnmodificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnmodificar.IconMarginLeft = 11;
            this.btnmodificar.IconPadding = 10;
            this.btnmodificar.IconRight = null;
            this.btnmodificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnmodificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnmodificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnmodificar.IconSize = 25;
            this.btnmodificar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnmodificar.IdleBorderRadius = 0;
            this.btnmodificar.IdleBorderThickness = 0;
            this.btnmodificar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnmodificar.IdleIconLeftImage = null;
            this.btnmodificar.IdleIconRightImage = null;
            this.btnmodificar.IndicateFocus = false;
            this.btnmodificar.Location = new System.Drawing.Point(711, 235);
            this.btnmodificar.Name = "btnmodificar";
            this.btnmodificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnmodificar.OnDisabledState.BorderRadius = 1;
            this.btnmodificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnmodificar.OnDisabledState.BorderThickness = 1;
            this.btnmodificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnmodificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnmodificar.OnDisabledState.IconLeftImage = null;
            this.btnmodificar.OnDisabledState.IconRightImage = null;
            this.btnmodificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnmodificar.onHoverState.BorderRadius = 1;
            this.btnmodificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnmodificar.onHoverState.BorderThickness = 1;
            this.btnmodificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnmodificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnmodificar.onHoverState.IconLeftImage = null;
            this.btnmodificar.onHoverState.IconRightImage = null;
            this.btnmodificar.OnIdleState.BorderColor = System.Drawing.Color.HotPink;
            this.btnmodificar.OnIdleState.BorderRadius = 1;
            this.btnmodificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnmodificar.OnIdleState.BorderThickness = 1;
            this.btnmodificar.OnIdleState.FillColor = System.Drawing.Color.HotPink;
            this.btnmodificar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnmodificar.OnIdleState.IconLeftImage = null;
            this.btnmodificar.OnIdleState.IconRightImage = null;
            this.btnmodificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnmodificar.OnPressedState.BorderRadius = 1;
            this.btnmodificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnmodificar.OnPressedState.BorderThickness = 1;
            this.btnmodificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnmodificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnmodificar.OnPressedState.IconLeftImage = null;
            this.btnmodificar.OnPressedState.IconRightImage = null;
            this.btnmodificar.Size = new System.Drawing.Size(128, 46);
            this.btnmodificar.TabIndex = 2;
            this.btnmodificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnmodificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnmodificar.TextMarginLeft = 0;
            this.btnmodificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnmodificar.UseDefaultRadiusAndThickness = true;
            this.btnmodificar.Click += new System.EventHandler(this.btnmodificar_Click);
            // 
            // btneliminar
            // 
            this.btneliminar.AllowAnimations = true;
            this.btneliminar.AllowMouseEffects = true;
            this.btneliminar.AllowToggling = false;
            this.btneliminar.AnimationSpeed = 200;
            this.btneliminar.AutoGenerateColors = false;
            this.btneliminar.AutoRoundBorders = false;
            this.btneliminar.AutoSizeLeftIcon = true;
            this.btneliminar.AutoSizeRightIcon = true;
            this.btneliminar.BackColor = System.Drawing.Color.Transparent;
            this.btneliminar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btneliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btneliminar.BackgroundImage")));
            this.btneliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneliminar.ButtonText = "Eliminar";
            this.btneliminar.ButtonTextMarginLeft = 0;
            this.btneliminar.ColorContrastOnClick = 45;
            this.btneliminar.ColorContrastOnHover = 45;
            this.btneliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btneliminar.CustomizableEdges = borderEdges4;
            this.btneliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btneliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneliminar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btneliminar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btneliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btneliminar.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btneliminar.ForeColor = System.Drawing.Color.Black;
            this.btneliminar.IconLeft = null;
            this.btneliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btneliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btneliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btneliminar.IconMarginLeft = 11;
            this.btneliminar.IconPadding = 10;
            this.btneliminar.IconRight = null;
            this.btneliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btneliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btneliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btneliminar.IconSize = 25;
            this.btneliminar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btneliminar.IdleBorderRadius = 0;
            this.btneliminar.IdleBorderThickness = 0;
            this.btneliminar.IdleFillColor = System.Drawing.Color.Empty;
            this.btneliminar.IdleIconLeftImage = null;
            this.btneliminar.IdleIconRightImage = null;
            this.btneliminar.IndicateFocus = false;
            this.btneliminar.Location = new System.Drawing.Point(711, 303);
            this.btneliminar.Name = "btneliminar";
            this.btneliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btneliminar.OnDisabledState.BorderRadius = 1;
            this.btneliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneliminar.OnDisabledState.BorderThickness = 1;
            this.btneliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btneliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btneliminar.OnDisabledState.IconLeftImage = null;
            this.btneliminar.OnDisabledState.IconRightImage = null;
            this.btneliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btneliminar.onHoverState.BorderRadius = 1;
            this.btneliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneliminar.onHoverState.BorderThickness = 1;
            this.btneliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btneliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btneliminar.onHoverState.IconLeftImage = null;
            this.btneliminar.onHoverState.IconRightImage = null;
            this.btneliminar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(106)))), ((int)(((byte)(255)))));
            this.btneliminar.OnIdleState.BorderRadius = 1;
            this.btneliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneliminar.OnIdleState.BorderThickness = 1;
            this.btneliminar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(57)))), ((int)(((byte)(106)))), ((int)(((byte)(255)))));
            this.btneliminar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btneliminar.OnIdleState.IconLeftImage = null;
            this.btneliminar.OnIdleState.IconRightImage = null;
            this.btneliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneliminar.OnPressedState.BorderRadius = 1;
            this.btneliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btneliminar.OnPressedState.BorderThickness = 1;
            this.btneliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btneliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btneliminar.OnPressedState.IconLeftImage = null;
            this.btneliminar.OnPressedState.IconRightImage = null;
            this.btneliminar.Size = new System.Drawing.Size(128, 43);
            this.btneliminar.TabIndex = 3;
            this.btneliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btneliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btneliminar.TextMarginLeft = 0;
            this.btneliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btneliminar.UseDefaultRadiusAndThickness = true;
            this.btneliminar.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // txtnombre
            // 
            this.txtnombre.AcceptsReturn = false;
            this.txtnombre.AcceptsTab = false;
            this.txtnombre.AnimationSpeed = 200;
            this.txtnombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnombre.AutoSizeHeight = true;
            this.txtnombre.BackColor = System.Drawing.Color.Transparent;
            this.txtnombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnombre.BackgroundImage")));
            this.txtnombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtnombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtnombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtnombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnombre.BorderRadius = 1;
            this.txtnombre.BorderThickness = 1;
            this.txtnombre.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtnombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnombre.DefaultText = "";
            this.txtnombre.FillColor = System.Drawing.Color.White;
            this.txtnombre.HideSelection = true;
            this.txtnombre.IconLeft = null;
            this.txtnombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.IconPadding = 10;
            this.txtnombre.IconRight = null;
            this.txtnombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.Lines = new string[0];
            this.txtnombre.Location = new System.Drawing.Point(266, 19);
            this.txtnombre.MaxLength = 32767;
            this.txtnombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnombre.Modified = false;
            this.txtnombre.Multiline = false;
            this.txtnombre.Name = "txtnombre";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnombre.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnIdleState = stateProperties4;
            this.txtnombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtnombre.PasswordChar = '\0';
            this.txtnombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnombre.PlaceholderText = "Enter text";
            this.txtnombre.ReadOnly = false;
            this.txtnombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnombre.SelectedText = "";
            this.txtnombre.SelectionLength = 0;
            this.txtnombre.SelectionStart = 0;
            this.txtnombre.ShortcutsEnabled = true;
            this.txtnombre.Size = new System.Drawing.Size(337, 41);
            this.txtnombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnombre.TabIndex = 4;
            this.txtnombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnombre.TextMarginBottom = 0;
            this.txtnombre.TextMarginLeft = 3;
            this.txtnombre.TextMarginTop = 1;
            this.txtnombre.TextPlaceholder = "Enter text";
            this.txtnombre.UseSystemPasswordChar = false;
            this.txtnombre.WordWrap = true;
            // 
            // txttelefono
            // 
            this.txttelefono.AcceptsReturn = false;
            this.txttelefono.AcceptsTab = false;
            this.txttelefono.AnimationSpeed = 200;
            this.txttelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txttelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txttelefono.AutoSizeHeight = true;
            this.txttelefono.BackColor = System.Drawing.Color.Transparent;
            this.txttelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txttelefono.BackgroundImage")));
            this.txttelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txttelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txttelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txttelefono.BorderRadius = 1;
            this.txttelefono.BorderThickness = 1;
            this.txttelefono.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txttelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txttelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txttelefono.DefaultText = "";
            this.txttelefono.FillColor = System.Drawing.Color.White;
            this.txttelefono.HideSelection = true;
            this.txttelefono.IconLeft = null;
            this.txttelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.IconPadding = 10;
            this.txttelefono.IconRight = null;
            this.txttelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.Lines = new string[0];
            this.txttelefono.Location = new System.Drawing.Point(266, 87);
            this.txttelefono.MaxLength = 32767;
            this.txttelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txttelefono.Modified = false;
            this.txttelefono.Multiline = false;
            this.txttelefono.Name = "txttelefono";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txttelefono.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnIdleState = stateProperties8;
            this.txttelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txttelefono.PasswordChar = '\0';
            this.txttelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txttelefono.PlaceholderText = "Enter text";
            this.txttelefono.ReadOnly = false;
            this.txttelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txttelefono.SelectedText = "";
            this.txttelefono.SelectionLength = 0;
            this.txttelefono.SelectionStart = 0;
            this.txttelefono.ShortcutsEnabled = true;
            this.txttelefono.Size = new System.Drawing.Size(337, 36);
            this.txttelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txttelefono.TabIndex = 5;
            this.txttelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txttelefono.TextMarginBottom = 0;
            this.txttelefono.TextMarginLeft = 3;
            this.txttelefono.TextMarginTop = 1;
            this.txttelefono.TextPlaceholder = "Enter text";
            this.txttelefono.UseSystemPasswordChar = false;
            this.txttelefono.WordWrap = true;
            // 
            // txtcorreo
            // 
            this.txtcorreo.AcceptsReturn = false;
            this.txtcorreo.AcceptsTab = false;
            this.txtcorreo.AnimationSpeed = 200;
            this.txtcorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtcorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtcorreo.AutoSizeHeight = true;
            this.txtcorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtcorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtcorreo.BackgroundImage")));
            this.txtcorreo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtcorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtcorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtcorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtcorreo.BorderRadius = 1;
            this.txtcorreo.BorderThickness = 1;
            this.txtcorreo.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtcorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtcorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtcorreo.DefaultText = "";
            this.txtcorreo.FillColor = System.Drawing.Color.White;
            this.txtcorreo.HideSelection = true;
            this.txtcorreo.IconLeft = null;
            this.txtcorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.IconPadding = 10;
            this.txtcorreo.IconRight = null;
            this.txtcorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.Lines = new string[0];
            this.txtcorreo.Location = new System.Drawing.Point(266, 144);
            this.txtcorreo.MaxLength = 32767;
            this.txtcorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtcorreo.Modified = false;
            this.txtcorreo.Multiline = false;
            this.txtcorreo.Name = "txtcorreo";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtcorreo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnIdleState = stateProperties12;
            this.txtcorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtcorreo.PasswordChar = '\0';
            this.txtcorreo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtcorreo.PlaceholderText = "Enter text";
            this.txtcorreo.ReadOnly = false;
            this.txtcorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtcorreo.SelectedText = "";
            this.txtcorreo.SelectionLength = 0;
            this.txtcorreo.SelectionStart = 0;
            this.txtcorreo.ShortcutsEnabled = true;
            this.txtcorreo.Size = new System.Drawing.Size(337, 39);
            this.txtcorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtcorreo.TabIndex = 6;
            this.txtcorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtcorreo.TextMarginBottom = 0;
            this.txtcorreo.TextMarginLeft = 3;
            this.txtcorreo.TextMarginTop = 1;
            this.txtcorreo.TextPlaceholder = "Enter text";
            this.txtcorreo.UseSystemPasswordChar = false;
            this.txtcorreo.WordWrap = true;
            // 
            // txtdireccion
            // 
            this.txtdireccion.AcceptsReturn = false;
            this.txtdireccion.AcceptsTab = false;
            this.txtdireccion.AnimationSpeed = 200;
            this.txtdireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdireccion.AutoSizeHeight = true;
            this.txtdireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtdireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdireccion.BackgroundImage")));
            this.txtdireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdireccion.BorderRadius = 1;
            this.txtdireccion.BorderThickness = 1;
            this.txtdireccion.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtdireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtdireccion.DefaultText = "";
            this.txtdireccion.FillColor = System.Drawing.Color.White;
            this.txtdireccion.HideSelection = true;
            this.txtdireccion.IconLeft = null;
            this.txtdireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.IconPadding = 10;
            this.txtdireccion.IconRight = null;
            this.txtdireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.Lines = new string[0];
            this.txtdireccion.Location = new System.Drawing.Point(266, 210);
            this.txtdireccion.MaxLength = 32767;
            this.txtdireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdireccion.Modified = false;
            this.txtdireccion.Multiline = false;
            this.txtdireccion.Name = "txtdireccion";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdireccion.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnIdleState = stateProperties16;
            this.txtdireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtdireccion.PasswordChar = '\0';
            this.txtdireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdireccion.PlaceholderText = "Enter text";
            this.txtdireccion.ReadOnly = false;
            this.txtdireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdireccion.SelectedText = "";
            this.txtdireccion.SelectionLength = 0;
            this.txtdireccion.SelectionStart = 0;
            this.txtdireccion.ShortcutsEnabled = true;
            this.txtdireccion.Size = new System.Drawing.Size(337, 39);
            this.txtdireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdireccion.TabIndex = 7;
            this.txtdireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdireccion.TextMarginBottom = 0;
            this.txtdireccion.TextMarginLeft = 3;
            this.txtdireccion.TextMarginTop = 1;
            this.txtdireccion.TextPlaceholder = "Enter text";
            this.txtdireccion.UseSystemPasswordChar = false;
            this.txtdireccion.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(51, 144);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(53, 21);
            this.bunifuLabel3.TabIndex = 10;
            this.bunifuLabel3.Text = "Correo";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(51, 87);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(66, 21);
            this.bunifuLabel5.TabIndex = 12;
            this.bunifuLabel5.Text = "Telefono";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(51, 19);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(63, 21);
            this.bunifuLabel2.TabIndex = 13;
            this.bunifuLabel2.Text = "Nombre";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(51, 210);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(73, 21);
            this.bunifuLabel1.TabIndex = 14;
            this.bunifuLabel1.Text = "Dirección";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // datetimepicker
            // 
            this.datetimepicker.BackColor = System.Drawing.Color.Transparent;
            this.datetimepicker.BorderColor = System.Drawing.Color.Silver;
            this.datetimepicker.BorderRadius = 1;
            this.datetimepicker.Color = System.Drawing.Color.Silver;
            this.datetimepicker.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.datetimepicker.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.datetimepicker.DisabledColor = System.Drawing.Color.Gray;
            this.datetimepicker.DisplayWeekNumbers = false;
            this.datetimepicker.DPHeight = 0;
            this.datetimepicker.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.datetimepicker.FillDatePicker = false;
            this.datetimepicker.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.datetimepicker.ForeColor = System.Drawing.Color.Black;
            this.datetimepicker.Icon = ((System.Drawing.Image)(resources.GetObject("datetimepicker.Icon")));
            this.datetimepicker.IconColor = System.Drawing.Color.Gray;
            this.datetimepicker.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.datetimepicker.LeftTextMargin = 5;
            this.datetimepicker.Location = new System.Drawing.Point(266, 264);
            this.datetimepicker.MinimumSize = new System.Drawing.Size(4, 32);
            this.datetimepicker.Name = "datetimepicker";
            this.datetimepicker.Size = new System.Drawing.Size(337, 32);
            this.datetimepicker.TabIndex = 15;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(51, 275);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(135, 21);
            this.bunifuLabel4.TabIndex = 16;
            this.bunifuLabel4.Text = "Fecha de Ingreso";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.datetimepicker);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.txtnombre);
            this.bunifuPanel1.Controls.Add(this.txttelefono);
            this.bunifuPanel1.Controls.Add(this.txtdireccion);
            this.bunifuPanel1.Controls.Add(this.txtcorreo);
            this.bunifuPanel1.Location = new System.Drawing.Point(29, 50);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(647, 334);
            this.bunifuPanel1.TabIndex = 17;
            // 
            // Clientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.ClientSize = new System.Drawing.Size(1000, 450);
            this.Controls.Add(this.btnmodificar);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.btneliminar);
            this.Controls.Add(this.btnbuscar);
            this.Controls.Add(this.btnagregar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Clientes";
            this.Text = "Clientes";
            this.Load += new System.EventHandler(this.Clientes_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnagregar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnbuscar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnmodificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btneliminar;
        private Bunifu.UI.WinForms.BunifuTextBox txtnombre;
        private Bunifu.UI.WinForms.BunifuTextBox txttelefono;
        private Bunifu.UI.WinForms.BunifuTextBox txtcorreo;
        private Bunifu.UI.WinForms.BunifuTextBox txtdireccion;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDatePicker datetimepicker;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
    }
}